[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "observe live dirt include sun twice patch vanish swamp window floor vocal ready very adapt awake patch noise foot suggest chuckle seminar erode open"
balance = 100_000_000_000_000

[devnet]
pox_stacking_orders = []
