[project]
name = 'stacksport-dca'
description = 'DCA Vault contract for StacksPort'
authors = []
telemetry = false

[[project.requirements]]
contract_id = 'SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.xyk-core-v-1-2'

[[project.requirements]]
contract_id = 'SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.xyk-pool-sbtc-stx-v-1-1'

[[project.requirements]]
contract_id = 'SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.xyk-pool-trait-v-1-2'

[[project.requirements]]
contract_id = 'SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.sip-010-trait-ft-standard-v-1-1'

[[project.requirements]]
contract_id = 'SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.token-stx-v-1-2'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'


[contracts.dca-vault]
path = 'dca-vault.clar'
clarity_version = 3
epoch = '3.0'

[contracts.bitflow-sbtc-swap-router]
path = 'bitflow-sbtc-swap-router.clar'
clarity_version = 3
epoch = '3.0'

